In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [3]:
data= pd.read_csv("age_salary.csv",index_col=0)
data.head(5)

Gender  Age  Salary Purchased
ID                                 
1001    Male   21   21000        No
1002    Male   37   22000        No
1003  Female   28   45000        No
1004  Female   29   59000        No
1005    Male   21   78000        No

# Min Max Scalar

In [7]:
x_real= data.iloc[:,[1,2]]

## formula= Xi-Xmin/Xmax-Xmin 

In [8]:
minmaxscalar= preprocessing.MinMaxScaler(feature_range=(0, 1))
feature_scale=minmaxscalar.fit_transform(x_real)

In [9]:
feature_scale

array([[0.02439024, 0.02962963],
       [0.41463415, 0.03703704],
       [0.19512195, 0.20740741],
       [0.2195122 , 0.31111111],
       [0.02439024, 0.45185185],
       [0.2195122 , 0.31851852],
       [0.2195122 , 0.51111111],
       [0.34146341, 1.        ],
       [0.17073171, 0.13333333],
       [0.41463415, 0.37037037],
       [0.19512195, 0.48148148],
       [0.19512195, 0.27407407],
       [0.04878049, 0.52592593],
       [0.34146341, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26829268, 0.48148148],
       [0.70731707, 0.07407407],
       [0.65853659, 0.08148148],
       [0.68292683, 0.0962963 ],
       [0.73170732, 0.1037037 ],
       [0.65853659, 0.05185185],
       [0.70731707, 0.25185185],
       [0.73170732, 0.19259259],
       [0.65853659, 0.05185185],
       [0.68292683, 0.05925926],
       [0.70731707, 0.03703704],
       [0.75609756, 0.0962963 ],
       [0.70731707, 0.11111111],
       [0.26829268, 0.20740741],
       [0.31707317, 0.02222222],
       [0.

# Standard Scaler

In [10]:
x_real= data.iloc[:,[1,2]]

# # formula= Xi-Xmean/(standard deviation of that feature)

In [11]:
standardscaler= preprocessing.StandardScaler()
feature_scale=standardscaler.fit_transform(x_real)

In [12]:
feature_scale

array([[-1.52370992, -1.34479807],
       [ 0.62804284, -1.31234638],
       [-0.58231809, -0.56595749],
       [-0.44783354, -0.11163382],
       [-1.52370992,  0.50494831],
       [-0.44783354, -0.07918213],
       [-0.44783354,  0.76456184],
       [ 0.22458919,  2.90637344],
       [-0.71680264, -0.8904744 ],
       [ 0.62804284,  0.14797971],
       [-0.58231809,  0.63475507],
       [-0.58231809, -0.27389227],
       [-1.38922537,  0.82946522],
       [ 0.22458919, -1.37724976],
       [-1.65819447,  0.69965846],
       [-0.17886445,  0.63475507],
       [ 2.2418574 , -1.15008793],
       [ 1.97288831, -1.11763623],
       [ 2.10737285, -1.05273285],
       [ 2.37634195, -1.02028116],
       [ 1.97288831, -1.247443  ],
       [ 2.2418574 , -0.37124734],
       [ 2.37634195, -0.63086087],
       [ 1.97288831, -1.247443  ],
       [ 2.10737285, -1.21499131],
       [ 2.2418574 , -1.31234638],
       [ 2.5108265 , -1.05273285],
       [ 2.2418574 , -0.98782947],
       [-0.17886445,

# Normalizer

In [13]:
x_real= data.iloc[:,[1,2]]

# #formula= Xi/square of all the value of that row

In [14]:
normalizer= preprocessing.Normalizer()
feature_scale=normalizer.fit_transform(x_real)

In [15]:
feature_scale

array([[9.99999500e-04, 9.99999500e-01],
       [1.68181580e-03, 9.99998586e-01],
       [6.22222102e-04, 9.99999806e-01],
       [4.91525364e-04, 9.99999879e-01],
       [2.69230759e-04, 9.99999964e-01],
       [4.83333277e-04, 9.99999883e-01],
       [3.37209283e-04, 9.99999943e-01],
       [2.23684205e-04, 9.99999975e-01],
       [7.71428342e-04, 9.99999702e-01],
       [5.52238722e-04, 9.99999848e-01],
       [3.41463395e-04, 9.99999942e-01],
       [5.18518449e-04, 9.99999866e-01],
       [2.49999992e-04, 9.99999969e-01],
       [1.69999754e-03, 9.99998555e-01],
       [2.38095231e-04, 9.99999972e-01],
       [3.78048753e-04, 9.99999929e-01],
       [1.81481183e-03, 9.99998353e-01],
       [1.67856906e-03, 9.99998591e-01],
       [1.59999795e-03, 9.99998720e-01],
       [1.61290113e-03, 9.99998699e-01],
       [1.95832958e-03, 9.99998082e-01],
       [9.60783870e-04, 9.99999538e-01],
       [1.16278991e-03, 9.99999324e-01],
       [1.95832958e-03, 9.99998082e-01],
       [1.919996

# Binarizer

In [18]:
binarizer= preprocessing.Binarizer(21)
feature_scale=binarizer.fit_transform(x_real)

In [19]:
feature_scale

array([[0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1,